/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        // Primary Brand - mapped to CSS variables
        primary: {
          DEFAULT: 'var(--color-primary)',
          light: 'var(--color-primary-light)',
          dark: 'var(--color-primary-dark)',
        },
        // Tencent Blue Scale (mapped to CSS variables)
        tencent: {
          blue: 'var(--color-primary)',
          'blue-light': 'var(--color-primary-light)',
          'blue-dark': 'var(--color-primary-dark)',
          50: '#E0EBFF',
          100: '#B4CEFF',
          200: '#87B1FF',
          300: '#5B95FF',
          400: '#2E79FF',
          500: '#0052D9',
          600: '#0041A8',
          700: '#00317A',
          800: '#00204D',
          900: '#001026',
        },
        // Goose-specific Colors
        goose: {
          orange: 'var(--color-goose-orange)',
          'orange-light': 'var(--color-goose-orange-light)',
          green: '#2BA471',
          red: '#D54941',
          warning: '#E37318',
        },
        // Functional Colors (semantic mapping)
        success: {
          DEFAULT: 'var(--color-success)',
          light: '#48BB78',
          dark: '#278A5E',
          50: '#E6F7EE',
          100: '#C3EED5',
          200: '#A0E4BC',
          300: '#7DDAA3',
          400: '#5AD08A',
          500: '#2BA471',
          600: '#258E62',
          700: '#1F7853',
          800: '#196244',
          900: '#134C35',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          light: '#F09040',
          dark: '#C9610F',
          50: '#FFF3E6',
          100: '#FFE0C2',
          200: '#FFCD9E',
          300: '#FFBA7A',
          400: '#FFA756',
          500: '#E37318',
          600: '#C9610F',
          700: '#AF4F06',
          800: '#953D00',
          900: '#7B2B00',
        },
        error: {
          DEFAULT: 'var(--color-error)',
          light: '#E56B63',
          dark: '#B83B34',
          50: '#FCEAEA',
          100: '#F6CCCC',
          200: '#F0AEAE',
          300: '#EA9090',
          400: '#E47272',
          500: '#D54941',
          600: '#B83B34',
          700: '#9B2D27',
          800: '#7E1F1A',
          900: '#61110D',
        },
        info: {
          DEFAULT: 'var(--color-info)',
          light: 'var(--color-primary-light)',
          dark: 'var(--color-primary-dark)',
        },
        // Neutral Gray Scale (mapped to CSS variables)
        gray: {
          1: 'var(--gray-1)',
          2: 'var(--gray-2)',
          3: 'var(--gray-3)',
          4: 'var(--gray-4)',
          5: 'var(--gray-5)',
          6: 'var(--gray-6)',
          7: 'var(--gray-7)',
          8: 'var(--gray-8)',
          9: 'var(--gray-9)',
          10: 'var(--gray-10)',
          11: 'var(--gray-11)',
          12: 'var(--gray-12)',
        },
        // Background & Surface Colors
        bg: {
          page: 'var(--bg-page)',
          surface: 'var(--bg-surface)',
          'surface-elevated': 'var(--bg-surface-elevated)',
          overlay: 'var(--bg-overlay)',
          disabled: 'var(--bg-disabled)',
        },
        // Text Colors
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          disabled: 'var(--text-disabled)',
          inverse: 'var(--text-inverse)',
        },
        // Border Colors
        border: {
          DEFAULT: 'var(--border-color-base)',
          light: 'var(--border-color-light)',
          dark: 'var(--border-color-dark)',
          focus: 'var(--border-color-focus)',
          error: 'var(--border-color-error)',
        },
      },
      boxShadow: {
        '1': 'var(--shadow-1)',
        '2': 'var(--shadow-2)',
        '3': 'var(--shadow-3)',
        '4': 'var(--shadow-4)',
        '5': 'var(--shadow-5)',
        'soft': 'var(--shadow-2)',
        'medium': 'var(--shadow-3)',
        'strong': 'var(--shadow-5)',
        'button': 'var(--shadow-button)',
        'button-hover': 'var(--shadow-button-hover)',
        'card': 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        'modal': 'var(--shadow-modal)',
        'dropdown': 'var(--shadow-dropdown)',
        'focus': 'var(--shadow-focus)',
        'glow-blue': '0 0 20px rgba(0, 82, 217, 0.3)',
        'glow-purple': '0 0 20px rgba(75, 142, 255, 0.3)',
        'glow-green': '0 0 20px rgba(43, 164, 113, 0.3)',
        'glow-orange': '0 0 20px rgba(255, 159, 67, 0.3)',
      },
      backgroundImage: {
        // Tencent Brand Gradients (腾讯蓝主导)
        'gradient-primary': 'linear-gradient(135deg, #0052D9 0%, #4B8EFF 100%)',
        'gradient-blue': 'linear-gradient(135deg, #0052D9 0%, #003CAB 100%)',
        'gradient-purple': 'linear-gradient(135deg, #4B8EFF 0%, #00317A 100%)',
        'gradient-green': 'linear-gradient(135deg, #2BA471 0%, #278A5E 100%)',
        'gradient-orange': 'linear-gradient(135deg, #FF9F43 0%, #E37318 100%)',
        'gradient-pink': 'linear-gradient(135deg, #EC4899 0%, #DB2777 100%)',
        // Tencent 8th Anniversary Brand Colors (蓝→紫→粉)
        'gradient-anniversary': 'linear-gradient(135deg, #0052D9 0%, #8B5CF6 50%, #EC4899 100%)',
        // Mesh and Aurora Gradients
        'gradient-mesh': 'radial-gradient(at 0% 0%, hsla(216,100%,36%,1) 0, transparent 50%), radial-gradient(at 50% 0%, hsla(225,39%,30%,1) 0, transparent 50%), radial-gradient(at 100% 0%, hsla(216,100%,50%,1) 0, transparent 50%)',
        'mesh-gradient-1': 'linear-gradient(135deg, #F5F7FA 0%, #E0EBFF 25%, #B4CEFF 50%, #E6F7EE 75%, #F5F7FA 100%)',
        'mesh-gradient-2': 'radial-gradient(circle at 20% 50%, rgba(0, 82, 217, 0.15), transparent 50%), radial-gradient(circle at 80% 80%, rgba(75, 142, 255, 0.15), transparent 50%)',
        'aurora': 'linear-gradient(125deg, #B4CEFF 0%, #E0EBFF 50%, #E6F7EE 100%)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'float-fast': 'float 4s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'pulse-soft': 'pulse-soft 3s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'slide-up': 'slide-up 0.6s ease-out',
        'slide-down': 'slide-down 0.6s ease-out',
        'fade-in': 'fade-in 0.8s ease-out',
        'scale-in': 'scale-in 0.3s ease-out',
        'bounce-soft': 'bounce-soft 2s infinite',
        'spin-slow': 'spin 3s linear infinite',
        'blob': 'blob 7s infinite',
        // "自树而生"主题动画
        'grow-up': 'grow-up 3s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'grow-up-slow': 'grow-up 4s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'branch-extend': 'branch-extend 2s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'sway-gentle': 'sway-gentle 4s ease-in-out infinite',
        'rise-float': 'rise-float 5s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 8s ease infinite',
        'leaf-rustle': 'leaf-rustle 3s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.8', transform: 'scale(1.05)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(0, 82, 217, 0.5), 0 0 20px rgba(0, 82, 217, 0.3)' },
          '100%': { boxShadow: '0 0 10px rgba(0, 82, 217, 0.8), 0 0 40px rgba(0, 82, 217, 0.5)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-down': {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'bounce-soft': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        // "自树而生"主题关键帧
        'grow-up': {
          '0%': { opacity: '0', transform: 'translateY(30px) scaleY(0.8)', transformOrigin: 'bottom center' },
          '100%': { opacity: '1', transform: 'translateY(0) scaleY(1)', transformOrigin: 'bottom center' },
        },
        'branch-extend': {
          '0%': { scaleX: '0', transformOrigin: 'left center' },
          '100%': { scaleX: '1', transformOrigin: 'left center' },
        },
        'sway-gentle': {
          '0%, 100%': { transform: 'rotate(-2deg) translateX(0)' },
          '50%': { transform: 'rotate(2deg) translateX(3px)' },
        },
        'rise-float': {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '25%': { transform: 'translateY(-12px) rotate(1deg)' },
          '75%': { transform: 'translateY(-6px) rotate(-1deg)' },
        },
        'gradient-shift': {
          '0%, 100%': { backgroundPosition: '0% 30%' },
          '50%': { backgroundPosition: '100% 70%' },
        },
        'leaf-rustle': {
          '0%, 100%': { transform: 'rotate(0deg) scale(1)' },
          '25%': { transform: 'rotate(3deg) scale(1.02)' },
          '75%': { transform: 'rotate(-2deg) scale(0.98)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '0': 'var(--space-0)',
        'px': 'var(--space-1)',
        '0.5': 'var(--space-1)',
        '1': 'var(--space-2)',
        '1.5': 'var(--space-3)',
        '2': 'var(--space-3)',
        '2.5': 'var(--space-4)',
        '3': 'var(--space-4)',
        '3.5': 'var(--space-5)',
        '4': 'var(--space-5)',
        '5': 'var(--space-6)',
        '6': 'var(--space-7)',
        '7': 'var(--space-7)',
        '8': 'var(--space-8)',
        '9': 'var(--space-9)',
        '10': 'var(--space-10)',
        '11': 'var(--space-11)',
        '12': 'var(--space-12)',
        '14': 'var(--space-14)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
      },
      borderRadius: {
        'none': '0',
        'sm': 'var(--radius-sm)',
        'DEFAULT': 'var(--radius-md)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        'full': 'var(--radius-full)',
        'button': 'var(--radius-button)',
        'input': 'var(--radius-input)',
        'card': 'var(--radius-card)',
        'modal': 'var(--radius-modal)',
        'badge': 'var(--radius-badge)',
      },
      animationDelay: {
        '2000': '2s',
        '4000': '4s',
      },
      zIndex: {
        'hide': 'var(--z-hide)',
        'base': 'var(--z-base)',
        'dropdown': 'var(--z-dropdown)',
        'sticky': 'var(--z-sticky)',
        'fixed': 'var(--z-fixed)',
        'overlay': 'var(--z-overlay)',
        'modal': 'var(--z-modal)',
        'popover': 'var(--z-popover)',
        'tooltip': 'var(--z-tooltip)',
        'toast': 'var(--z-toast)',
      },
      transitionDuration: {
        'instant': 'var(--duration-instant)',
        'fast': 'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow': 'var(--duration-slow)',
        'slower': 'var(--duration-slower)',
      },
      transitionTimingFunction: {
        'out': 'var(--ease-out)',
        'in': 'var(--ease-in)',
        'in-out': 'var(--ease-in-out)',
        'bounce': 'var(--ease-bounce)',
        'smooth': 'var(--ease-smooth)',
      },
      fontSize: {
        'xs': ['var(--font-size-xs)', { lineHeight: 'var(--line-height-tight)' }],
        'sm': ['var(--font-size-sm)', { lineHeight: 'var(--line-height-base)' }],
        'base': ['var(--font-size-base)', { lineHeight: 'var(--line-height-base)' }],
        'lg': ['var(--font-size-lg)', { lineHeight: 'var(--line-height-base)' }],
        'xl': ['var(--font-size-xl)', { lineHeight: 'var(--line-height-tight)' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-tight)' }],
        '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-tight)' }],
        '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
        '5xl': ['var(--font-size-5xl)', { lineHeight: 'var(--line-height-tight)' }],
        '6xl': ['var(--font-size-6xl)', { lineHeight: 'var(--line-height-tight)' }],
      },
      letterSpacing: {
        'tight': 'var(--letter-spacing-tight)',
        'base': 'var(--letter-spacing-base)',
        'wide': 'var(--letter-spacing-wide)',
      },
      lineHeight: {
        'tight': 'var(--line-height-tight)',
        'base': 'var(--line-height-base)',
        'relaxed': 'var(--line-height-relaxed)',
      },
      borderWidth: {
        'thin': 'var(--border-width-thin)',
        'base': 'var(--border-width-base)',
        'thick': 'var(--border-width-thick)',
      },
      maxWidth: {
        'sm': 'var(--container-sm)',
        'md': 'var(--container-md)',
        'lg': 'var(--container-lg)',
        'xl': 'var(--container-xl)',
        '2xl': 'var(--container-2xl)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    function({ addUtilities }) {
      const newUtilities = {
        '.animation-delay-2000': {
          'animation-delay': '2s',
        },
        '.animation-delay-4000': {
          'animation-delay': '4s',
        },
      };
      addUtilities(newUtilities);
    },
  ],
};
